# Generated by Django 4.2.5 on 2023-12-13 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medipal_app', '0002_disease_symptom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='disease',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
